accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import signup


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path

from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path

from tasks.views import  TaskCreateView, TaskListView, TaskUpdateView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy


urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(User, related_name="projects")

    def __str__(self):
        return self.name


# Create your models here.

tasks/models.py
from django.db import models
from projects.models import Project
from django.contrib.auth.models import User

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE, null=True
    )
    assignee = models.ForeignKey(
        User, related_name="tasks", on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return str(self.name)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User
from django.contrib.auth import login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {"form": form})

projects/views.py
from django.shortcuts import redirect
from projects.models import Project
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/projectlist.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/projectdetail.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/createproject.html"
    fields = ["name", "description", "members"]

    def form_valid(self, form):
        item = form.save()
        item.user = self.request.user
        item.save()
        return redirect("show_project", pk=item.id)

tasks/views.py
from django.shortcuts import redirect
from tasks.models import Task
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.
class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/createtask.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def form_valid(self, form):
        item = form.save()
        item.assignee = self.request.user
        item.save()
        return redirect("create_task")


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/viewtask.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

accounts/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta http-equiv='X-UA-Compatible' content='IE=edge'>
        <title>Page Title</title>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
        <script src='main.js'></script>
    </head>

    <body>
        <header>
            <nav>
                <ul>{% if user.is_authenticated %}
                    <li>
                        <a href="{% url "show_my_tasks" %}">My tasks</a>
                    </li>
                    <li>
                        <a href="{% url "list_projects"  %}">My projects</a>
                    </li>
                    <li>
                        <a href="{% url "logout" %}">Logout</a>
                    </li>
                {% else%}
                    <li>
                        <a href="{% url "login" %}">"Login"</a>
                    </li>
                    <li>
                        <a href="{% url "signup" %}">Signup</a>
                    </li>
                {% endif %}
                </ul>
            </nav>

        </header>
        {% block content %}
        {% endblock content %}
    </body>

</html>

projects/templates/projects/createproject.html
{% extends "../base.html" %}

{% block content %}

    <main>
        <div>
            <h1>Create a new Project</h1>
            <form method="post">
                {% csrf_token %} {{ form.as_p}}
                <button type="submit">Create</button>

            </div>
        </main>
{%endblock content%}

projects/templates/projects/projectdetail.html
{% extends "../base.html" %}
{% load markdownify %}

{% block content %}

    <main>
        <div>
            <h2>
                <p><a href="{% url 'create_task'%}"> create_task</a></p>
            </h2>
            <h1>
                {{project.name}}
            </h1>
            {{ project.description|markdownify }}
            <h2>Tasks</h2>
            {%if project.tasks.all|length > 0%}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date<th>
                                <th>Is completed<th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for task in project.tasks.all %}
                                        <tr>
                                            <td>{{ task.name }}</td>
                                            <td>{{ task.assignee }}</td>
                                            <td>{{ task.start_date }}</td>
                                            <td>{{ task.due_date }}</td>
                                            <td>{{ task.is_completed}}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
            {%else%}
                <p>"This project has no tasks"</p>
            {%endif%}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/projectlist.html
{% extends "../base.html" %}

{% block content %}
    <main>
        <div>
            <h1>
                <p>My Projects</p>
            </h1>
            <h2>
                <p><a href="{% url 'create_project'%}"> Create Project</a></p>
            </h2>
            {%if not project_list.all %}
                <p>You are not assigned to any projects</p>
            {%else%}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of tasks</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in project_list %}
                            <tr>
                                <td>  <a href="{% url 'show_project' project.pk %}">{{ project.name }}</a>  </td>

                                <td>{{ project.tasks.all|length }}</td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            {%endif%}
        </div>
        <div>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/createtask.html
{% extends "../base.html" %}

{% block content %}
    <main>
        <div>
            <h1>Create a new Task</h1>
            <form method="post">
                {% csrf_token %} {{ form.as_p}}
                <button type="submit">Create</button>

            </div>
        </main>
{% endblock content %}

tasks/templates/tasks/viewtask.html
{% extends "../base.html" %}
{% block content %}
    <main>
        <div>
            <h1>
                My Tasks
            </h1>
            {%if task_list.all|length > 0%}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed<th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for task in task_list %}
                                    <tr>
                                        <td>{{ task.name }}</td>
                                        <td>{{ task.start_date }}</td>
                                        <td>{{ task.due_date }}</td>
                                        <td>
                                            {%if task.is_completed == False%}
                                                <form method="post" action="{% url 'complete_task' task.id %}">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="is_completed" value="True">
                                                    <button>Complete</button>
                                                </form>
                                            {%endif%}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
            {%else%}
                <p>"You have no tasks"</p>
            {%endif%}
        </div>
    </main>
{% endblock content %}